name: Spec

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.ts'
  push:
    branches:
      - main
    paths:
      - 'src/**/*.ts'

jobs:
  spec:
    name: Spec

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up BunJS
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Specs
        run: bun test
